baseURL: https://luckmu.github.io/
languageCode: en-us
title: Luckmu's writepad
copyright: Luckmu
theme: blank

paginate: 5

menus:
  main:
    - name: Tags
      url: tags/
      weight: 1
    - name: Categories
      url: categories/
      weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true
